### ISSUE TITLE
Upon Login (this is Hinata someone has my damn mame on here)

### ISSUE THREAD

**Issue by Noctre** [Eclipse-/EclipseUI#1]
basically logged in and changed resolutions to my native one and this popped up can't quite explain why

Message: Interface\AddOns\ecUnitframes\layout.lua:16: attempt to index field 'theme' (a nil value)
Time: 11/06/10 01:07:34
Count: 1
Stack: Interface\AddOns\ecUnitframes\layout.lua:16: in main chunk

Locals: normTex = "Interface\AddOns\Tukui\media\textures\normTex"
backdrop = <table> {
 insets = <table> {
 }
}
media = <table> {
 custom_texture_1 = "Interface\AddOns\Tukui\media\textures\empath"
 custom_font_3 = "Interface\Addons\Tukui\media\fonts\caith.ttf"
 normTex = "Interface\AddOns\Tukui\media\textures\normTex"
 whisper = "Interface\AddOns\Tukui\media\sounds\whisper.mp3"
 custom_font_4 = "Interface\Addons\Tukui\media\fonts\zrnic.ttf"
 dmgfont = "Interface\AddOns\Tukui\media\fonts\combat_font.ttf"
 glowTex = "Interface\AddOns\Tukui\media\textures\glowTex"
 custom_font_1 = "Interface\Addons\Tukui\media\fonts\visitor2.ttf"
 uffont = "Interface\AddOns\Tukui\media\fonts\uf_font.ttf"
 backdropcolor = <table> {
 }
 blank = "Interface\AddOns\Tukui\media\textures\blank"
 altbordercolor = <table> {
 }
 font = "Interface\Addons\Tukui\media\fonts\arial.ttf"
 warning = "Interface\AddOns\Tukui\media\sounds\warning.mp3"
 bubbleTex = "Interface\AddOns\Tukui\media\textures\bubbleTex"
 buttonhover = "Interface\AddOns\Tukui\media\textures\button_hover"
 fadedbackdropcolor = <table> {
 }
 bordercolor = <table> {
 }
 custom_font_2 = "Interface\Addons\Tukui\media\fonts\visitor_rus.ttf"
}
unitframes = <table> {
 health_color = <table> {
 }
 combatfeedback = true
 auratextscale = 11
 runebar = true
 auratimer = true
 totemtimer = true
 showtotalhpmp = false
 showplayerinparty = false
 raidunitdebuffwatch = true
 unitcastbar = true
 targetauras = true
 positionbychar = true
 playeraggro = true
 showsmooth = true
 charportrait = true
 enable = true
 ws_show_target = true
 ws_show_player = true
 highThreshold = 80
 showboss = true
 targetpowerpvponly = true
 gridhealthvertical = true
 healcomm = false
 showrange = true
 focusdebuffs = false
 showsymbols = true
 raidalphaoor = 0.3
 lowThreshold = 20
 aggro = true
 health_bg_color = <table> {
 }
 playerauras = false
 classcolor = false
 mainassist = false
 maintank = false
 showthreat = true
 showfocustarget = false
 cbclasscolor = true
 cblatency = false
 cbicons = true
 totdebuffs = false
}
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index field 'theme' (a nil value)"

**Comment by Eclipse-** [comment]
You need to sleep more :D
