### ISSUE TITLE
raid frames, auto accept/repair/sell

### ISSUE THREAD

**Issue by kilii** [Eclipse-/EclipseUI#12]
not getting an lua error but sometimes when i join a raid before other people the next 2-3 frames all display my name instead of theirs, if you select it's a different person.  fixes with a /rl

the auto accept/repair/sell isn't working atm for me either, checked the default config to make sure they were set to true but doesn't seem to be working in game

**Comment by Eclipse-** [comment]
I read about the name problem the other day and it'll be fixed with the next update.

I guess I should remove some options from the config that currently aren't available in-game to clear up any confusion.
