### ISSUE TITLE
Datatext is on the wrong side

### ISSUE THREAD

**Issue by ottopatrick** [Eclipse-/EclipseUI#13]
The datatext is atm on the left side of the minimap and the expand button doesn´t match with the size of the datatext.

**Comment by Eclipse-** [comment]
I know, it's something I need to finish.

**Comment by ottopatrick** [comment]
Eclipse has done that already and do it too after he release, but thanks  ;-)

**Comment by Eclipse-** [comment]
Placement is fixed in latest.
