### ISSUE TITLE
just 2 little small things :) 

### ISSUE THREAD

**Issue by kaindruid** [Eclipse-/EclipseUI#15]
HC 25 man flag still on right side & in healer mode targets casting bar behind the grid :) 

http://www.tukui.org/v2/forums/topic.php?id=4997&page=2

sorry posted it on tuk forum too :s

keep up the good work

**Comment by Eclipse-** [comment]
It's cool, I replied to your post on the forums anyway.

Thanks for pointing out the minimap flag, I thought that would've moved with the minimap. I'll set that up tomorrow :)
