### ISSUE TITLE
unit frames texture

### ISSUE THREAD

**Issue by kilii** [Eclipse-/EclipseUI#16]
is there a way to get back the old texture and colour for the unit frames ? I tried just changing the texture in the lua but i couldn't find a place to change the colour for it as well :(

Don't know if it'd take you long to do but the old frames looked a lot nicer with the darker colour and a texture on them rather than just being completely flat

**Comment by Eclipse-** [comment]
The texture still exists within the UI. It's known as "custom_texture_1". Just changed TukuiCF["general"].game_texture within config.lua to that.
