### ISSUE TITLE
LUA error: Databar

### ISSUE THREAD

**Issue by Banishga** [Eclipse-/EclipseUI#18]
When toggling through the 3 databars at the center top of the screen, trying to decide which I want to display, this LUA error appears.

<pre>
Date: 2010-11-29 05:44:33
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Tukui\datatext\databar.lua line 195:
   TukuiDataFrame1:SetPoint(): TukuiDataFrame2 is dependent on this
Debug:

   Tukui\datatext\databar.lua:195:
      Tukui\datatext\databar.lua:190
   Tukui\datatext\databar.lua:215:
      Tukui\datatext\databar.lua:200
   Tukui\datatext\databar.lua:258:
      Tukui\datatext\databar.lua:254
</pre>

**Comment by Eclipse-** [comment]
Thanks banishga, fixed!
