### ISSUE TITLE
LUA error: Keyring

### ISSUE THREAD

**Issue by Banishga** [Eclipse-/EclipseUI#19]
Shows up when I left click on Keyring button in bag.

<pre>
Date: 2010-11-29 06:22:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Tukui\scripts\bags.lua line 954:
   attempt to call field 'SkinFadedPanel' (a nil value)
Debug:

   Tukui\scripts\bags.lua:954:
      Tukui\scripts\bags.lua:949

   ..\FrameXML\ContainerFrame.lua:544: ContainerFrame_GenerateFrame()
   ..\FrameXML\ContainerFrame.lua:876: ToggleKeyRing()
   Tukui\scripts\bags.lua:485:
      Tukui\scripts\bags.lua:484
</pre>

**Comment by Eclipse-** [comment]
Fixed, thanks.
