### ISSUE TITLE
EclipseUI from a healer perspective.

### ISSUE THREAD

**Issue by ermik** [Eclipse-/EclipseUI#23]
Hello Eclipse,
I am a Holy Paladin. I heal stuff, and it's very fourtune for me if stuff doesn't die. :]

So, here are couple of thoughts about your UI that will make healer's life easier, some I've rasied before.
1. Lets look at the raid frames. They are neat indeed. But you are unable to quickly respond to how the health of a unit behave, because some time you need to **literally** peer into the UFrames to see something. Why is that?
   
   That is first of all because the colors of the actual health and background are very similar, if we look at it from a distance we cant really see the difference.
   
   Second. The Unit name is there all the time, and I ask: for what particular reason? If you have ever used Grid you know that  name of a Unit becomes its HP or his HP loss after certain % and it perfectly makes sense.
   
   And a quick tip: we all like font you are using in your UI, but I call people by their class name now, because in raid frames most of the time thir names are unreadable fast enough.
2. For the love of god make minimap bigger... Mostly as a person wuth a gathering proffesion I struggle to see something in there but if I use it to actually see where people are its even more furstrating. I suggest x1.5 increase or somewhat bigger.
3. This is very neat way to show debuffs. This frame around UF. Cool. But, I kinda needed to ask anyway, why there is no debuffs shown by default on the target? Seriously what teh hell? Is it dangerous? Does he need it or not? Do we need to run away from him? How should I answer all these questions if there is no debuff icon? You dont need to make a LUA drama about that, there is pretty clear Blizzard settings that do all the job. Just read them and use in your UI.

**Comment by ermik** [comment]
4. The out-of-range frame should still be configured so you can see HP of a person - 
   "Do I need to run there through fire to heal him or not?"

Very good raid frames setting could be seen in [here, watch in 720p](http://www.youtube.com/watch?v=FPEs9O-Bpa0) 

The UI page: [click, its shit overall thou](http://www.tankspot.com/showthread.php?54528-aliena-s-ui)

**Comment by daeyron** [comment]
1) change unit frames to class color. in /config/default-config.lua (approx. line 60), change:

```
["classcolor"] = false,
```

to 
    ["classcolor"] = true,

and you should have much more visible frames.

2) you can change the size of the minimap in /scripts/minimap.lua. i'll grant that something like a size toggle for the minimap would be helpful for gathering, but remember that this is a minimalistic ui. 

3) again, try configuring in default-config.lua, approx. line 66-67, change:

```
["onlyplayerdebuffs"] = true,
["onlyplayerbuffs"] = true,
```

to:
    ["onlyplayerdebuffs"] = false,
    ["onlyplayerbuffs"] = false,

and see if that fixes your problem. 

4) i play with class-colored raid frames (also a holy paladin) and can see the health of out of range targets. try changing that (as described in #1) and see if you still have this problem. 

good luck!
