### ISSUE TITLE
Sorry bro..

### ISSUE THREAD

**Issue by t-pb** [Eclipse-/EclipseUI#24]
You deffs miss me nagging you on IRC though.

Soon as i hit esc & interface, the secondary bars popped out, not using the buttons though so there are no borders etc round them :(

**Comment by t-pb** [comment]
Nevermind.

**Comment by Eclipse-** [comment]
https://github.com/Eclipse-/EclipseUI/commit/ed915696e2626bfa45379cab5cf4e3056059509e

Let me know if it still occurs.
