### ISSUE TITLE
"chat" > background = true  error

### ISSUE THREAD

**Issue by Rotoboy** [Eclipse-/EclipseUI#25]
Just fyi -

1x Tukui-T4.00\modules\chat\chatframes.lua:225: attempt to index global 'TukuiChatBackgroundRight' (a nil value)
Tukui-T4.00\modules\chat\chatframes.lua:251: in function <Tukui\modules\chat\chatframes.lua:242>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_ENTERING_WORLD"
addon = nil
SetupChat = <function> @ Tukui\modules\chat\chatframes.lua:166:
SetupChatPosAndFont = <function> @ Tukui\modules\chat\chatframes.lua:187:

---

**Comment by Eclipse-** [comment]
https://github.com/Eclipse-/EclipseUI/commit/238109f3e147e46b0aefd542b337d8d25e09f41a

Thanks, shouldn't have left that option in there.
