### ISSUE TITLE
Combo Points?

### ISSUE THREAD

**Issue by DoubleAgent41** [Eclipse-/EclipseUI#27]
I noticed there are no combo points for Rogues/Kitty Druids. Bug or implemented design?

**Comment by Eclipse-** [comment]
Implemented. I always hated the oUF combo points and usually used my own, Smelly has developed his own addon that did exactly the same thing called sCombo. Very worth checking out!

**Comment by DoubleAgent41** [comment]
Alright, thanks for the quick reply! =)

**Comment by Eclipse-** [comment]
Np :)

**Comment by Pariah** [comment]
Installing the default sCombo does not seem to be working. I receive the following error:

Message: Interface\AddOns\sCombo\sCombo.lua:5: attempt to index field 'CPoints' (a nil value)
Time: 02/18/11 21:22:27
Count: 1
Stack: Interface\AddOns\sCombo\sCombo.lua:5: in main chunk

Locals: T = <table> {
 countOffsets = <table> {
 }
 stancebuttonsize = 27
 Scale = <function> defined @Interface\AddOns\Tukui\core\api.lua:17
 PostUpdateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:565
 AchievementMove = <function> defined @Interface\AddOns\Tukui\modules\blizzard\achievements.lua:18
 resolution = 15
 dummy = <function> defined @Interface\AddOns\Tukui\core\constants.lua:3
 petbuttonsize = 27
 getscreenheight = 1080
 level = 69
 CreatePanel = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:29
 CheckCast = <function> defined @Interface\AddOns\Tukui\core\functions.lua:619
 MoverFrames = <table> {
 }
 remindbuffs = <table> {
 }
 SetTemplate = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:79
 UpdateShards = <function> defined @Interface\AddOns\Tukui\core\functions.lua:627
 PostAchievementMove = <function> defined @Interface\AddOns\Tukui\modules\blizzard\achievements.lua:68
 UpdateManaLevel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:710
 myclass = "ROGUE"
 PP = <function> defined @Interface\AddOns\Tukui\modules\datatext\setup.lua:13
 getscreenwidth = 1920
 ShortValue = <function> defined @Interface\AddOns\Tukui\core\functions.lua:214
 Role = "Melee"
 UIScale = <function> defined @Interface\AddOns\Tukui\core\uiscale.lua:3
 Target = 225
 ColorTemplate = <table> {
 }
 CustomCastDelayText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:480
 myname = "Xcut"
 CreateAuraWatchIcon = <function> defined @Interface\AddOns\Tukui\core\functions.lua:813
 PostUpdateHealth = <function> defined @Interface\AddOns\Tukui\core\functions.lua:306
 UpdateHoly = <function> defined @Interface\AddOns\Tukui\core\functions.lua:648
 DataTextTooltipAnchor = <function> defined @Interface\AddOns\Tukui\core\functions.lua:11
 TukuiShiftBarUpdate = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:141
 CreateShadow = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:90
 buttonspacing = 4
 PostNamePosition = <function> defined @Interface\AddOns\Tukui\core\functions.lua:404
 SPELL_FILTER = <function> defined @Interface\AddOns\Tukui\modules\chat\spam.lua:14
 myrealm = "Lightninghoof"
 CustomCastTimeText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:476
 PostCreateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:525
 EclipseDisplay = <function> defined @Interface\AddOns\Tukui\core\functions.lua:670
 HidePortrait = <function> defined @Interface\AddOns\Tukui\core\functions.lua:595
 getscreenresolution = "1920x1080"
 CheckChannel = <function> defined @Interface\AddOns\Tukui\core\functions.lua:623
 CreateTransparentPanel = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:47
 PostUpdateHealthRaid = <function> defined @Interface\AddOns\Tukui\core\functions.lua:365
 Player = 225
 ToT = 130
 version = "T4.00"
 raidscale = 1
 oUF_colors = <table> {
 }
 EclipseDirection = <function> defined @Interface\AddOns\Tukui\core\functions.lua:660
 UpdateDruidMana = <function> defined @Interface\AddOns\Tukui\core\functions.lua:726
 Focus = 115
 Boss = 200
 StylePet = <function> defined @Interface\AddOns\Tukui\modules\actionbars\Style.lua:131
 Kill = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:108
 PostUpdatePower = <function> defined @Interface\AddOns\Tukui\core\functions.lua:423
 cEnd = ""
 Phasing = <function> defined @Interface\AddOns\Tukui\core\functions.lua:639
 SpawnMenu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:265
 FUCKYOU_GOLDSPAMMERS = <function> defined @Interface\AddOns\Tukui\modules\chat\spam.lua:34
 PreUpdatePower = <function> defined @Interface\AddOns\Tukui\core\functions.lua:414
 mult = 1
 patch = "4.0.6"
 buffids = <table> {
 }
 UpdateThreat = <function> defin
