### ISSUE TITLE
Disabled Action bars problem.

### ISSUE THREAD

**Issue by Tebryn** [Eclipse-/EclipseUI#29]
Right side chat frame distorts when Tukui Action Bars are disabled. The tab bar for it stays matching the left side, the chat panel itself though grows 3-4 times taller. 

The panels for the action bars also continue to exist. at fully extended settings with no retract hovers. Honestly this works for me and my bar addon. allowing an easier time matching tukui theme. but the tooltip is anchoring to the right tab bar while the rightbar panel is still existing. so I am doubting this is intended.

**Comment by Eclipse-** [comment]
Ok, I know why it's doing this, will fix tomorrow!

Thanks!

**Comment by Eclipse-** [comment]
Fixed. Upload coming soon.
