### ISSUE TITLE
Left Chat Moves in Windowed Mode

### ISSUE THREAD

**Issue by Rotoboy** [Eclipse-/EclipseUI#30]
No error but if you switch to windowed mode the left chat tabs move requiring a /rl to correct.

Here's a SS.

http://img33.imageshack.us/i/euiwindowmode.jpg/

**Comment by Eclipse-** [comment]
Was this with a clean WTF installation?

**Comment by Rotoboy** [comment]
It was, yes.  Just reinstalled and had the same issue.

**Comment by Eclipse-** [comment]
I'm going to close this ticket because there is another ticket open with the same issue. The issue is being looked into.
