### ISSUE TITLE
Rested state

### ISSUE THREAD

**Issue by Rinthe** [Eclipse-/EclipseUI#31]
How can I tell if I'm rested or not?

**Comment by Eclipse-** [comment]
EclipseUI doesn't come with an experience bar, that's why I built Tukui_Experience which can be found on my GitHub as well. It's not completed but majority of it works! 

If you're using it then there will be a slightly darker status bar behind the experience bar.

**Comment by Rinthe** [comment]
I do have Tukui_Experience. I don't see the darker status you're talking about.

**Comment by Eclipse-** [comment]
Apologies, my mistake. Fix incoming.
