### ISSUE TITLE
after playing in the config

### ISSUE THREAD

**Issue by Noctre** [Eclipse-/EclipseUI#32]
Message: ...ce\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:843: attempt to index field 'Buffs' (a nil value)
Time: 02/18/11 22:49:55
Count: 1
Stack: ...ce\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:843: in function `styleFunc'
...ace\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:227: in function <...ace\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:181>
(tail call): ?
...ace\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:518: in function`Spawn'
...ce\AddOns\Tukui\modules\unitframes\layouts\tukui.lua:1049: in main chunk

Locals: self = TukuiFocus {
 0 = <userdata>
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:144
 unit = "focus"
 UNIT_PET = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:144
 RaidIcon = <unnamed> {
 }
 __elements = <table> {
 }
 ufbg = <unnamed> {
 }
 Power = <unnamed> {
 }
 Name = <unnamed> {
 }
 Castbar = TukuiFocusCastBar {
 }
 colors = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:124
 Health = <unnamed> {
 }
 menu = <function> defined @Interface\AddOns\Tukui\core\functions.lua:265
 UNIT_EXITED_VEHICLE = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\ouf.lua:144
 style = "Tukui"
}
unit = "focus"
InvFrame = <unnamed> {
 0 = <userdata>
}
RaidIcon = <unnamed> {
 0 = <userdata>
}
health = <unnamed> {
 oborder = <unnamed> {
 }
 colorClass = false
 frequentUpdates = true
 colorTapping = false
 colorDisconnected = false
 0 = <userdata>
 bg = <unnamed> {
 }
 Smooth = true
}
healthBG = <unnamed> {
 0 = <userdata>
}
power = <unnamed> {
 0 = <userdata>
 colorTapping = true
 colorClass = true
 colorReaction = true
 oborder = <unnamed> {
 }
 colorDisconnected = true
 frequentUpdates = true
 bg = <unnamed> {
 }
 Smooth = true
}
powerBG = <unnamed> {
 0 = <userdata>
 multiplier = 0.3
}
ufbg = <unnamed> {
 oborder = <unnamed> {
 }
 shadow = <unnamed> {
 }
 0 = <userdata>
}
panel = <unnamed> {
 0 = <userdata>
}
castbar = TukuiFocusCastBar {
 0 = <userdata>
 Text = <unnamed> {
 }
 PostCastStart = <function> defined @Interface\AddOns\Tukui\core\functions.lua:619
 time = <unnamed> {
 }
 Time = <unnamed> {
 }
 CustomTimeText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:476
 PostChannelStart = <function> defined @Interface\AddOns\Tukui\core\functions.lua:623
 CustomDelayText = <function> defined @Interface\AddOns\Tukui\core\functions.lua:480
}
castbarBG = <unnamed> {
 0 = <userdata>
 shadow = <unnamed> {
 }
 overlay = <unnamed> {
 }
}
Name = <unnamed> {
 parent = TukuiFocus {
 }
 UpdateTag = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\elements\tags.lua:552
 0 = <userdata>
}
debuffs = <unnamed> {
 0 = <userdata>
}
(_temporary) = <function> defined =[C]:-1
(_temporary) = <unnamed> {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = <unnamed> {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = <userdata>
(_temporary) = <table> {
 1 = <unnamed> {
 }
}
(_temporary) = <unnamed> {
 parent = TukuiFocus {
 }
 UpdateTag = <function> defined @Interface\AddOns\Tukui\modules\unitframes\core\oUF\elements\tags.lua:552
 0 = <userdata>
}
(_temporary) = <function> defined =[C]:-1
(_temporary) = nil
(_temporary) = "[Tukui:namelong]"
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index field 'Buffs' (a nil value)"
T = <table> {
 countOffsets = <table> {
 }
 stancebuttonsize = 27
 Scale = <function> defined @Interface\AddOns\Tukui\core\api.lua:17
 PostUpdateAura = <function> defined @Interface\AddOns\Tukui\core\functions.lua:565
 resolution = 11
 dummy = <function> defined @Interface\AddOns\Tukui\core\constants.lua:3
 petbuttonsize = 27
 getscreenheight = 1080
 level = 70
 CreatePanel = <function> defined @Interface\AddOns\Tukui\core\deprecated.lua:29
 CheckCast = <function> defined @Interface\AddOns\Tukui\core\functions.lua:619
 remindbuffs = <table> {
 }
 S

**Comment by shagster** [comment]
More info: This occurs when disabling target auras.

**Comment by Eclipse-** [comment]
Fixed. Will be uploaded shortly.
