### ISSUE TITLE
Chattab align after relog

### ISSUE THREAD

**Issue by nicedevil-tukui** [Eclipse-/EclipseUI#33]
after relogging into the game and the loot chat frame is moved to the left, we got this

http://www.abload.de/img/wowscrnshot_021911_081ssw0.jpg

**Comment by Eclipse-** [comment]
Is this with a clean WTF folder installation?

**Comment by daeyron** [comment]
You can fix this with /resetui.

**Comment by nicedevil-tukui** [comment]
i did a full clean install. after i log off and log in the same prob again! /resetui doesn't help

**Comment by nicedevil-tukui** [comment]
oh forgot to say, that a /rl will fix it, but i think that isn't the way u want to let it there or? everytime you log in you have to /rl :/

**Comment by Eclipse-** [comment]
It's definitely not intended for you to /resetui or /rl every time you log into WoW etc.

It seems to be a problem with windowed mode, so I'll take a look at that.

**Comment by nicedevil-tukui** [comment]
yeah right, i have 1920x1080 full screen window mode on

**Comment by nicedevil-tukui** [comment]
tryed this now with fullscreen (real fullscreen oc) => same issue :/ has nothing to do with windowed fullscreen or windowed mode

**Comment by Eclipse-** [comment]
I'm at a bit of a loss here. I've freshly installed the UI across multiple characters using a multitude of different resolution sizes (windowed and fullscreen) and I can't replicate the issue.

I'm not saying the issue doesn't exist, because multiple users have it, however I must be missing something. So if you've got anything else, let me know.

**Comment by nicedevil-tukui** [comment]
with last release it seems to be fixed, tryed it with twinks and on another PC now... bug is gone for me now :)

**Comment by nicedevil-tukui** [comment]
with last release it seems to be fixed, tryed it with twinks and on another PC now... bug is gone for me now :)

**Comment by daeyron** [comment]
Not sure that I can post here, but I'm still encountering this bug. I think it may have something to do with changing the settings in the chat tabs, particularly the bottom right chat tab. Nicedevil was apparently deleting this tab (so it seems from his screenshot) and I've been setting it to show /2. 

I wonder whether this recent commit from Tukz is related: https://github.com/tukz/Tukui/commit/726567c017ce1826e9f9b669e5ca5b1289a6e9ef

I'll try to do a reinstall this weekend and avoid changing any of the tab settings to see if the problem can be avoided that way. It may be that the tab settings must be modified in the .lua to avoid messing up the alignment.
