### ISSUE TITLE
Cyrillic on CastBar/PetBar

### ISSUE THREAD

**Issue by Dartenes** [Eclipse-/EclipseUI#34]
Hi!
I play ruWoW with your UI, and I have trouble with castbar: when I'm casting any spell I see "??" instead of spell name, so please add cyrillic fonts.
Also, I have trouble with petbar: I can't use 1 or more buttons on petbar (it's different on every warlock pet, on felguard there is 1 bugged button, on voidwalker there is 3 bugged buttons).

**Comment by Eclipse-** [comment]
I'll be adding a font system today which should clear up the font problems :)

About the pet buttons bugging, can you explain further? Maybe a screenshot?

**Comment by Dartenes** [comment]
http://img19.imageshack.us/i/pet2l.jpg/ (as you can see, button 7 is empty)
http://img525.imageshack.us/i/pet22.jpg/ (there I've tried to move spell from petbutton 6 to 7, button 7 is still empty and spell has disappered so button 7 doesn't work)
http://img511.imageshack.us/i/pet1t.jpg/ (it's a screenshot from other pet, there is 3 bugged buttons: 5,6,7)

**Comment by Eclipse-** [comment]
Thank you for the shots.

A quick fix for your font problem before I implement:

Open medias.lua and find where it says "["pixel_font"]", it's near the bottom of the file. Then change the font path to this:

[[Interface\Addons\Tukui\medias\fonts\visitor_rus.ttf]]

So it should look like this:

```
["pixel_font"] = [[Interface\Addons\Tukui\medias\fonts\visitor_rus.ttf]],
```

**Comment by Dartenes** [comment]
Thank you very much. Still waiting for petbar fix.

**Comment by Eclipse-** [comment]
I had a quick look before I had to do some personal stuff and you're right, something is definitely wrong with 7th button. Will look into it asap.

**Comment by Eclipse-** [comment]
The problem seems to be appearing on multiple platforms of Tukui. Bear with me on this one.

**Comment by Dartenes** [comment]
That's not as important as previous bugs. but some text/symbols appeared behind minimap after medias.lua fix: http://img406.imageshack.us/i/minimapw.jpg/
Also, I think font "visitor_rus" needs to be more polished.

**Comment by Eclipse-** [comment]
Ok, had a look again at the petbar issue and checked it across multiple characters with pets.

Death Knight level 80+ works fine.
Hunter level 70+ works fine.
Warlock level 62, 7th button will not accept a skill, rest work fine.

I disabled Tukui to see if this happens on the Blizzard UI and it does, so it seems your limited to pet action buttons for what level you are.

Closing.
