### ISSUE TITLE
Tukui buffs/debuffs

### ISSUE THREAD

**Issue by amnel** [Eclipse-/EclipseUI#36]
Hi,

I tried to disable the tukui buffs/debuffs (top right corner ones).
On changing the config.lua entry nothing happen.

Also tried to overwrite the normal config via profiles.lua but
C.auras.player = false else didn't work.

They stay visible together with blizzards default buffs / debuffs

**Comment by ghost** [comment]
this "setting" applies to the player frame, not to the top buffs and debuffs I believe

**Comment by amnel** [comment]
No they don't ... config.lua have to sections for it

one under unitframes, which does what you mean ... and a stand alone section named auras, which controlls the behaviour of top right buff also know as tukz buffs / debuffs

@edit
Also there is no possibility to tweak the size of tukz buffs / debuffs and Cooldownfont, far to small for me

**Comment by Eclipse-** [comment]
Fixed. Upload coming soon.

Thanks!
