### ISSUE TITLE
/moveui again

### ISSUE THREAD

**Issue by amnel** [Eclipse-/EclipseUI#37]
Hi,

as mentioned befor, using /moveui turned the entire backround grey, overlapping everything not related to the ui. In addition to the first time, some moveable frames disappear. To be honest they're still there, but without the red border and beneath the grey backround - no chance to move them apart from clicking randomly over the screen.

**Comment by ghost** [comment]
This seems to happen when the shapeshift bar is disabled.

**Comment by amnel** [comment]
You're right, with "C.actionbar.hideshapeshiftbar = false" it works correctly.
But this is only a cosmetic solve :)

**Comment by Eclipse-** [comment]
Thanks guys, my mistake :)

Fixed. Upload coming soon!
