### ISSUE TITLE
Minor Bug on splitting Items

### ISSUE THREAD

**Issue by amnel** [Eclipse-/EclipseUI#39]
There seems to be a display failure on splitting stacks of Items.
The number of Items which will be splitt are not displayed in the frame.

Test it with different Layouts (heal / dps) and on maximised window mode / fullscreen mode

**Comment by Eclipse-** [comment]
Fixed, thank you.

https://github.com/Eclipse-/EclipseUI/commit/17c545cb7f51d3ccc3cfa0bfca94abb9d24d7deb
