### ISSUE TITLE
[Feedback] Unitframes

### ISSUE THREAD

**Issue by amnel** [Eclipse-/EclipseUI#40]
Hi again,

I'm doing some extensiv testing, for about 2 hours since last update.
I'm wondering if there is any way to disable focusbuffs? I just found focusdebuffs.

A possibility to edit fontsize of panels would be very nice too ... but thus far, great job!
Oh and I love to see a possibility to move the diffirent castbars.

Greetz
Amnel

**Comment by amnel** [comment]
After 3 hours of raiding with this ptv of your modification  ... 

Healthdisplay for focus target with percentHP would be great
In addition a automatic Raidlayout change from 10 man to 25 man when a 11th player is invited to the raid is kind of anyoing.

thus far ... amazing play with this modification, thumbs up!

**Comment by Eclipse-** [comment]
Thanks for the feedback Amnel. 

I did intend to add an option for disabling focusdebuffs but just haven't got around to doing so yet.

The reason the raid layout changes when the 11th player joins is purely because that format of unitframe doesn't look great when there is 25 of them. So if I don't switch at 11, where do I switch?

**Comment by amnel** [comment]
Hi,

at first thanks for your answer, shows that you consider on our feedback / reports.
Please don't overwork yourself, I'm very patient and absolutely understand that you have more things todo than just implement or even thing about what I want :)

The option to disable focusDEBUFFs already implemented, or am I wrong? What I love to see is the same option for focusBUFFs.

Regarding the layout, I do understand your point of good / bad looking for 10 / 25 man. But please keep in mind that in a 10 man group you also have some player for replacements etc. - so a switch at 16 players fit better, somehow.

best regards

amnel

**Comment by Eclipse-** [comment]
I'm always glad to hear user's opinions/feedback about the UI, it helps improve it :)

Apologies, I must have mis-read, went to sleep at 6am -.-, but definitely a possibility it will be added!

True, I raid as 10man myself and we sometimes keep a few spare in the raid, but saying that I am a healer. However, I'll change it to 16, so we can have a 15man group as the new style and see how that performs.

**Comment by amnel** [comment]
cheers! Thanks alot, I'll keep testing during todays raids :)
/close this issue for now ... and maybe back with some more feedback late on :)
