### ISSUE TITLE
Weapon buff timer

### ISSUE THREAD

**Issue by Lifja** [Eclipse-/EclipseUI#41]
The weapon buff timer for shamans (and probably rogues) doesn't align properly with the other buffs/auras. Fixed it myself by setting the local function UpdateWeapons to -14 instead of -17:

button.time:SetPoint("BOTTOM", 0, -14)

Oh, and a question! The castbars and the powerbars on the unitframes are classcolored. But then, why does the castbar on shamans have a slightly different color? D: Uploaded an image to show you what I mean.

http://i.imgur.com/08OY1.jpg

**Comment by Eclipse-** [comment]
Hahaha, I was reading through the buffs file while setting fonts up and was like, "why do I have 2 different anchor positions?" xD

Thanks! I'll look into the class color, although I know I've changed something because I'm not finished with it yet! :)

**Comment by Eclipse-** [comment]
New version uploaded, fixed and closing.
