### ISSUE TITLE
Health BG color (not a real issue)

### ISSUE THREAD

**Issue by nicedevil-tukui** [Eclipse-/EclipseUI#43]
i tested the healmode today. i put on the healthdeficit and then went to the HC dayli. directly into the first 2 trash groups one partymember died because i couldn't see the healthlost realy good. only the number on the unitframe shows me, that this guy lost some health. maybe you could add a red color gradient or little bit shiny color gradient to the background of the unitframes.

**Comment by Eclipse-** [comment]
Add to config in new version, closing.
