### ISSUE TITLE
LFG Button @ Minimap

### ISSUE THREAD

**Issue by nicedevil-tukui** [Eclipse-/EclipseUI#44]
if we move the minimap to the upper right corner, the tooltip of the LFG button is out of the screen.

**Comment by Eclipse-** [comment]
Thanks for all the help and feedback so far nicedevil. Got this fixed and trying a few other things out with the movers. Will be pushing a big version later today!

**Comment by nicedevil-tukui** [comment]
no prob, will test your release 17 minutes released before now ;)

**Comment by Eclipse-** [comment]
New version uploaded, fixed and closing.
