### ISSUE TITLE
Option to change font size on unit frames, bag, datatext, buff timer, cooldown timer etc

### ISSUE THREAD

**Issue by Rinthe** [Eclipse-/EclipseUI#53]
basically an option to change font size for all. I find the pixel font works well at 14, 12 is way too small for me. looking through the code to change all the font sizes = pain.

Hope it's not too hard to implement.

**Comment by Eclipse-** [comment]
Majority of all the code is now all in one file? How is that even hard to change now? It takes now 100x less time than it would have done before, be grateful for that change.

Just change the template value of 12 to 14 and then set every font to "nil".

**Comment by Rinthe** [comment]
sorry. I didn't have the latest version you uploaded.

I just downloaded the latest version. worked perfectly. THANK YOU!

**Comment by Eclipse-** [comment]
No problem.
