### ISSUE TITLE
Class bar question

### ISSUE THREAD

**Issue by Tbs098** [Eclipse-/EclipseUI#55]
My main is a Death Knight and I'm using Foof's rune addon with your UI. I find having two runes redundant but it's the only way that I know of to be able to show the class bars for my other characters. (namely my paladin's holy power readout) Is there a way to only disable DK runes and leave the others enabled?

**Comment by Eclipse-** [comment]
You can use configuration profiles but I'm going to add something to do with this within a day or two.

**Comment by Eclipse-** [comment]
Included within the next update, closing.
