### ISSUE TITLE
oUF_hTukz_Raid16_40.lua - Missing 'Dead, AFK'

### ISSUE THREAD

**Issue by Rotoboy** [Eclipse-/EclipseUI#56]
I'll be able to double check / confirm this tomorrow evening when I raid.  The SS I took didn't turn out for some reason, apologies.

I was looking through the DPS layout and noticed the following that seemed to be missing from the Heal layouts.  Specifically line 100.  I don't understand enough about .lua to know whether that matters or not but thought I'd let you know.

local name = health:CreateFontString(nil, 'OVERLAY')
name:SetFont(font1, 12, "MONOCHROMEOUTLINE")
name:Point("LEFT", t, "RIGHT", 4, 1)
self:Tag(name, '[Tukui:getnamecolor][Tukui:namemedium] [Tukui:dead][Tukui:afk]')
self.Name = name

**Comment by Eclipse-** [comment]
No need to double check as you're absolutely right. I usually use custom tags for my heal layout and haven't got round to creating them, even though I do need to since I need them for my raiding as well, expect them in soon though :P

**Comment by Eclipse-** [comment]
Closing this as they'll be included in the next update.
