### ISSUE TITLE
the bars of the totems ? (update Eclipse--EclipseUI-b949224)

### ISSUE THREAD

**Issue by rsean** [Eclipse-/EclipseUI#58]
Good evening Eclipsé, I say to you congratulation for your interface which is extra! I come to say to you just that you have to forget of activated the bars of the totems on your last update...
(update Eclipse--EclipseUI-b949224)
Could you it added again, thank you very much.
Good continuation to your projects and long life in your interfaces < 3

**Comment by rsean** [comment]
Hello Eclipsé
 sorry, I noticed that by changing the command in Config.lua : 
Line 109 ["vertical_shapeshift"] = false,  
-- (NOT FOR SHAMANS/TOTEMS) vertical or horizontal shapeshift bar
The totems are again available and movable.
Sorry for the disturbance, the good continuation on your projects ^^

**Comment by Eclipse-** [comment]
I should probably fix this as well, my bad, thank you! :)
