### ISSUE TITLE
Calendar bug

### ISSUE THREAD

**Issue by Assid** [Eclipse-/EclipseUI#6]
Hi there,

when I middleclick on the time datatext, I can hear the sound that opens the calendar, but it does not appear on the screen :/

Thanks =)

**Comment by Eclipse-** [comment]
It's definitely working for me :x

Have you changed anything? What resolution do you run in?

**Comment by Assid** [comment]
I was expecting that you say it x)
I didn't edit anything except default-config & launch.lua for actionbars numbers
I find this bug strange too because I can hear the open & close sound concerning the calendar, but it doesn't appear on the screen.
With original Tukui it's working, with your edit it's not.
I tried to clear my cache, deactivate all other addons, no lua errors, it just doesn't appear.
I play on Fr client, in 1440x900 reso.
Ps : sorry for my bad english ;)

**Comment by Eclipse-** [comment]
Here's from using your resolution and the FR client:
http://dl.dropbox.com/u/5487873/Tukui%204.0.1-Cataclysm/WoWScrnShot_111810_201624.jpg

Works perfectly fine for me :x

Have you tried a clean install of my edit? Not changing anything in the Lua files, log in and try click it again.

**Comment by Assid** [comment]
It seems that it's a weird mouse problem. When I invert rigth and middle click :

```
if btn == "MiddleButton" then
    if EclipseSettings.game_time == true then
        EclipseSettings.game_time = false
        EclipseSettings.local_time = true
    elseif EclipseSettings.local_time == true then
        EclipseSettings.game_time = true
        EclipseSettings.local_time = false
    end
elseif btn == "RightButton" then
    GameTimeFrame:Click()
end
```

the calendar appears with right click, but it doesn't switch between local and game time with middle click... the middle button is working perfectly because i binded it to a spell.

It seems that it's a bug on my side. I'll look at that. Thanks for your time ;)

**Comment by ottopatrick** [comment]
If you have a TukUI installed before you use this edit, you have to /resetui than it works for me
