### ISSUE TITLE
Lua error since Toc 4.03

### ISSUE THREAD

**Issue by nicedevil-tukui** [Eclipse-/EclipseUI#63]
this lua message wasn't there before i updated to the last commit! looks like, that it isn't a problem of your edit, but why it wasn't there before mhhh?

Message: Interface\FrameXML\ChatFrame.lua:3779: attempt to perform arithmetic on a nil value
Time: 02/28/11 17:19:45
Count: 1
Stack: Interface\FrameXML\ChatFrame.lua:3779: in function `ChatEdit_UpdateHeader'
Interface\FrameXML\ChatFrame.lua:3506: in function`ChatEdit_ResetChatType'
Interface\FrameXML\ChatFrame.lua:3576: in function <Interface\FrameXML\ChatFrame.lua:3562>
Interface\FrameXML\ChatFrame.lua:3586: in function `ChatEdit_DeactivateChat'
Interface\FrameXML\InterfaceOptionsPanels.lua:980: in function`InterfaceOptionsSocialPanelChatStyle_SetChatStyle'
Interface\FrameXML\InterfaceOptionsPanels.lua:909: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:896>

Locals: editBox = ChatFrame5EditBox {
 0 = <userdata>
 tabCompleteIndex = 1
 headerSuffix = ChatFrame5EditBoxHeaderSuffix {
 }
 focusLeft = ChatFrame5EditBoxFocusLeft {
 }
 focusRight = ChatFrame5EditBoxFocusRight {
 }
 chatFrame = ChatFrame5 {
 }
 addSpaceToAutoComplete = true
 focusMid = ChatFrame5EditBoxFocusMid {
 }
 header = ChatFrame5EditBoxHeader {
 }
}
type = "SAY"
info = <table> {
 colorNameByClass = true
 flashTab = false
 b = 1.000000059139
 r = 1.000000059139
 id = 2
 sticky = 1
 flashTabOnGeneral = false
 g = 1.000000059139
}
header = ChatFrame5EditBoxHeader {
 0 = <userdata>
}
headerSuffix = ChatFrame5EditBoxHeaderSuffix {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = nil
(_temporary) = ChatFrame5EditBoxHeader {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = "SAY"
(_temporary) = "_SEND"
(_temporary) = nil
(_temporary) = nil
(*temporary) = "attempt to perform arithmetic on a nil value"

**Comment by Eclipse-** [comment]
What did you do to make this happen?

**Comment by nicedevil-tukui** [comment]
mhhh i have a custom profiles.lua

```
C.unitframes.enemyhcolor = true
C.unitframes.healthBgColor = { .25, .25, .25 }
C.unitframes.focusdebuffs = false
C.unitframes.onlyselfdebuffs = false
C.unitframes.onlyselfbuffs = false
C.unitframes.healthdeficit = true
C.unitframes.maintank = false
C.unitframes.debuffHighlightFilter = false
C.unitframes.playerHighlight = false    
C.actionbar.hideshapeshift = false
C.actionbar.vertical_shapeshift = false
C.cooldown.treshold = 3
C.datatext.dur = 3
C.datatext.friends = 0
C.datatext.gold = 2
C.datatext.guild = 0
C.datatext.crit = 6
C.datatext.wowtime = 1
C.datatext.time24 = true
C.chat.justyfyRight = true
C.chat.background = true
C.nameplate.showhealth = true
C.nameplate.enhancethreat = true
C.nameplate.overlap = true
C.tooltip.hodecombat = true 
```
