### ISSUE TITLE
KeyRing not showing IconTexture

### ISSUE THREAD

**Issue by conker** [Eclipse-/EclipseUI#65]
Hey Eclipse

Titel sais it all. KeyRing is showing Tooltips properly, IconTexture is just beautiful black.

**Comment by conker** [comment]
Hrm. Wow restarted and Textures are okay again.. not sure if it was a Wow or a EclipseUI-Bug, sorry 4 spam

**Comment by Eclipse-** [comment]
I think I know what this problem is. Will check when I get home from work.
