### ISSUE TITLE
Rogue Rangeslot Weapon Buff missing

### ISSUE THREAD

**Issue by conker** [Eclipse-/EclipseUI#68]
Hey Eclipse

For some reason modules/buffs/buffs.lua is not tracking Rogue's Rangeslotweapon Poisons. I just had a look at the code, but I am not able to find a bug...

Tested with TrownWeapon and Instant and deadly posion.

Cheers!

**Comment by Eclipse-** [comment]
You can blame Blizzard for that. 

With the old Tukui buff coding we couldn't right-click off our buffs because they protected it and it tainted the UI. 

Now we use new secureauratemplates and they are are fucked by Blizzard.
