### ISSUE TITLE
unit frames

### ISSUE THREAD

**Issue by kilii** [Eclipse-/EclipseUI#7]
with the latest update you did the unitframes stopped working, they worked earlier today around um 6-7hours ago.

here's the lua error:

Message: Interface\AddOns\Tukui\unitframes\layout.lua:974: unexpected symbol near ')'
Time: 11/17/10 23:49:52
Count: 1
Stack: [C]: ?

Locals: 

tried deleting all the files and re-downloading to see if it was an issue with coding i'd changed that hadn't been overwritten or clashed but no luck.

**Comment by Eclipse-** [comment]
Was my fault, removed an extra "end" by accident :x

https://github.com/Eclipse-/EclipseUI/commit/6d4997dc3e7e6f4e16e9207139c58a1943444320

Thanks!
