### ISSUE TITLE
Chat Frames

### ISSUE THREAD

**Issue by Shankoh** [Eclipse-/EclipseUI#73]
Message: Interface\AddOns\Tukui\modules\chat\chatframes.lua:155: attempt to index local 'header' (a nil value)
Time: 03/09/11 13:00:09
Count: 1
Stack: Interface\AddOns\Tukui\modules\chat\chatframes.lua:155: in function <Interface\AddOns\Tukui\modules\chat\chatframes.lua:153>
[C]: in function `ChatEdit_UpdateHeader'
Interface\FrameXML\ChatFrame.lua:4081: in function <Interface\FrameXML\ChatFrame.lua:4052>
(tail call): ?
Interface\FrameXML\ChatFrame.lua:4203: in function`ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3825: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:2560: in function <Interface\FrameXML\ChatFrame.lua:2553>
[C]: in function`UseAction'
Interface\FrameXML\SecureTemplates.lua:275: in function `handler'
Interface\FrameXML\SecureTemplates.lua:543: in function <Interface\FrameXML\SecureTemplates.lua:491>

Locals: editBox = MacroEditBox {
 0 = <userdata>
}
header = nil
(_temporary) = "MacroEditBoxHeader"
(_temporary) = nil
(_temporary) = "MacroEditBox"
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to index local 'header' (a nil value)"
_G = <table> {
 ActionButton7FlyoutBorder = ActionButton7FlyoutBorder {
 }
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 KBASE_NUM_FAKE_CATEGORIES = 1
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 BOOKTYPE_PROFESSION = "professions"
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Toggles an additional optional actionbar on the right side of the screen."
 InterfaceOptionsDisplayPanelShowAggroPercentageText = InterfaceOptionsDisplayPanelShowAggroPercentageText {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 CONSOLIDATED_BUFFS_PER_ROW = 4
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @Interface\FrameXML\MoneyFrame.lua:199
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Battle.net may be unavailable."
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 InterfaceOptionsCombatTextPanelFCTDropDown_OnClick = <function> defined @Interface\FrameXML\InterfaceOptionsPanels.lua:1536
 TradeSkillInputBoxLeft = TradeSkillInputBoxLeft {
 }
 LFGTeleport = <function> defined =[C]:-1
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 AtlasLootItem_30_QA = AtlasLootItem_30_QA {
 }
 ChannelMemberButton10Name = ChannelMemberButton10Name {
 }
 UIDROPDOWNMENU_OPEN_MENU = FriendsDropDown {
 }
 Graphics_QualityText = Graphics_QualityText {
 }
 StuffingBag4_11IconTexture = StuffingBag4_11IconTexture {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 VOICEMACRO_4_Sc_1_FEMALE = "Help me attack!"
 MainMenuXPBarDiv8 = MainMenuXPBarDiv8 {
 }
 MultiBarBottomRightButton9Panel = MultiBarBottomRightButton9Panel {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 ChannelMemberButton10SpeakerFrameOn = ChannelMemberButton10SpeakerFrameOn {
 }
 Ev

**Comment by Eclipse-** [comment]
Can you post a screen shot of your Social tab from the Interface Options in-game.

**Comment by Shankoh** [comment]
http://i.imgur.com/fnxlE.jpg

**Comment by Eclipse-** [comment]
I meant something like this:
http://img716.imageshack.us/f/wowscrnshot031011184822.jpg/

**Comment by Shankoh** [comment]
when i log in i get this error

Message: Interface\FrameXML\OptionsPanelTemplates.lua:228: attempt to call method 'GetValue' (a nil value)
Time: 03/10/11 12:32:22
Count: 1
Stack: Interface\FrameXML\OptionsPanelTemplates.lua:228: in function <Interface\FrameXML\OptionsPanelTemplates.lua:220>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsPanels.lua:82: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:80>
Interface\FrameXML\InterfaceOptionsPanels.lua:837: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:836>
[C]: in function`pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:209: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:208>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:228: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:224>

Locals: control = InterfaceOptionsSocialPanelChatStyle {
 0 = <userdata>
 type = 2
 selectedValue = "im"
 tooltip = "When clicking the tab of a Chat Frame, the entry box will attach to it. Each window's entry box will maintain its own saved state and history."
 defaultValue = "im"
 initialize = <function> defined @Interface\FrameXML\InterfaceOptionsPanels.lua:935
 value = "im"
 cvar = "chatStyle"
 oldValue = "im"
 noResize = 1
}
(_temporary) = nil
(_temporary) = InterfaceOptionsSocialPanelChatStyle {
 0 = <userdata>
 type = 2
 selectedValue = "im"
 tooltip = "When clicking the tab of a Chat Frame, the entry box will attach to it. Each window's entry box will maintain its own saved state and history."
 defaultValue = "im"
 initialize = <function> defined @Interface\FrameXML\InterfaceOptionsPanels.lua:935
 value = "im"
 cvar = "chatStyle"
 oldValue = "im"
 noResize = 1
}
(*temporary) = "attempt to call method 'GetValue' (a nil value)"

http://i.imgur.com/BZx73.jpg
