### ISSUE TITLE
actionbar

### ISSUE THREAD

**Issue by kilii** [Eclipse-/EclipseUI#8]
which action bar is the one above the loot chat frame?  I've tried hiding the grid which worked before but it still leaves the background now.

tried to add "TukuiBar"n":Hide(true)" but it still left the background, just wondering if you could give me the line + file i need to change or just the file :p

**Comment by Eclipse-** [comment]
Because backgrounds don't hide when "showgrid" is set to false. Showgrid only removes the borders/backgrounds of the actionbar buttons.
