### ISSUE TITLE
data text

### ISSUE THREAD

**Issue by kilii** [Eclipse-/EclipseUI#9]
has the durability data text gone from tukui? or is the coding still there but it's not in the config file for your edit?

i liked being able to see what my current durability was of my items more than say seeing my current spellpower :/

**Comment by Eclipse-** [comment]
It's currently not in the files.

It'll be back tomorrow with the rest of the datatext.

**Comment by kilii** [comment]
awesome :) keep up the good work ^^ and i might be able to help out sometime in the near future with hosting since I'm setting up a server or 4 at my apartment for my network engineering course :p

read how much you were hating on github :D
